project 'task3.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'task3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'SwiftyBeaver'
  pod 'RxOptional'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'IQKeyboardManagerSwift'

  # Pods for warehouse

  target 'task3Tests' do
    inherit! :search_paths
    # Pods or testing
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'task3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
